# Generated by Django 4.2.20 on 2025-03-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_datasetupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
