# Generated by Django 4.2.20 on 2025-03-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_role_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='updated_by',
        ),
    ]
